class InvalidCPFError(Exception):
   ...

class InvalidTypeError(Exception):
   ...

class MissingOneKey(Exception):
    ...
class InvalidUniqueKeyError(Exception):
    ...

class InvalidUniqueKey(Exception):
    ...

class InvalidKeyError(Exception):
    ...
class anotherKeyError(Exception):
    ...